# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/BatteryStateArray.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/BehaviorFault.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/EStopStateArray.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/FootStateArray.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/LeaseArray.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/LeaseOwner.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/Metrics.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/MobilityParams.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/SystemFault.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/WiFiState.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/BatteryState.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/BehaviorFaultState.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/EStopState.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/Feedback.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/FootState.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/Lease.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/LeaseResource.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/PowerState.msg;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg/SystemFaultState.msg;/home/junette/catkin_ws/devel_isolated/spot_msgs/share/spot_msgs/msg/NavigateToAction.msg;/home/junette/catkin_ws/devel_isolated/spot_msgs/share/spot_msgs/msg/NavigateToActionGoal.msg;/home/junette/catkin_ws/devel_isolated/spot_msgs/share/spot_msgs/msg/NavigateToActionResult.msg;/home/junette/catkin_ws/devel_isolated/spot_msgs/share/spot_msgs/msg/NavigateToActionFeedback.msg;/home/junette/catkin_ws/devel_isolated/spot_msgs/share/spot_msgs/msg/NavigateToGoal.msg;/home/junette/catkin_ws/devel_isolated/spot_msgs/share/spot_msgs/msg/NavigateToResult.msg;/home/junette/catkin_ws/devel_isolated/spot_msgs/share/spot_msgs/msg/NavigateToFeedback.msg"
services_str = "/home/junette/catkin_ws/src/spot_ros/spot_msgs/srv/ListGraph.srv;/home/junette/catkin_ws/src/spot_ros/spot_msgs/srv/SetLocomotion.srv"
pkg_name = "spot_msgs"
dependencies_str = "std_msgs;geometry_msgs;actionlib_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "spot_msgs;/home/junette/catkin_ws/src/spot_ros/spot_msgs/msg;spot_msgs;/home/junette/catkin_ws/devel_isolated/spot_msgs/share/spot_msgs/msg;std_msgs;/opt/ros/melodic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/melodic/share/geometry_msgs/cmake/../msg;actionlib_msgs;/opt/ros/melodic/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
