(cl:defpackage spot_msgs-srv
  (:use )
  (:export
   "LISTGRAPH"
   "<LISTGRAPH-REQUEST>"
   "LISTGRAPH-REQUEST"
   "<LISTGRAPH-RESPONSE>"
   "LISTGRAPH-RESPONSE"
   "SETLOCOMOTION"
   "<SETLOCOMOTION-REQUEST>"
   "SETLOCOMOTION-REQUEST"
   "<SETLOCOMOTION-RESPONSE>"
   "SETLOCOMOTION-RESPONSE"
  ))

